version: '3'

services:
  omni-ai:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - HUGGINGFACE_EMAIL=${HUGGINGFACE_EMAIL}
      - HUGGINGFACE_PASSWD=${HUGGINGFACE_PASSWD}